export const MATERIAL_LABELS={resin:'Resin',clay:'Clay',fur:'Fur',glass:'Glass'};
export const MATERIAL_DEFAULTS={resin:{roughness:.22,textureScale:24,textureStrength:0},clay:{roughness:.78,textureScale:35,textureStrength:.045},fur:{roughness:.75,textureScale:30,textureStrength:.1,furLength:.22,furDensity:28000},glass:{roughness:.06,textureScale:24,textureStrength:0}};
export const COLORS=[['#15171A','Ink'],['#8F6146','Brown'],['#EF4444','Red'],['#F58D27','Orange'],['#EDBA30','Yellow'],['#3BCC94','Mint'],['#2CB9A6','Teal'],['#3693ED','Blue'],['#8955EF','Violet'],['#D753B1','Pink'],['#A6A7AE','Gray'],['#F1EEE9','Cream']];
export const EMPTY_LOCKS={material:false,color:false,expression:false,presence:false};
export const clone=value=>structuredClone(value);
export const round=value=>Math.round(value*1000)/1000;
export function randomName(previous=''){const first=['Milo','Luna','Oliver','Sage','Noah','Zoe','Finn','Ada','Theo','Iris','Arlo','Nora','Leo','Ruby','Remy','Maya','Jude','Cleo','Eli','Nova','Luca','Esme','Owen','Alma','Felix','Wren','Ezra','Pearl','Oscar','June','Rory','Isla','Hugo','Olive','Beau','Cora','Ari','Vera','Nico','Flora','Otis','Lyra','Kit','Maeve','Levi','Nell','Rio','Faye','Asa','Mabel','Enzo','Mira','Ivo','Daisy','Micah','Tess','Jasper','Lila','Basil','Thea','Rowan','Elio','Anya','Soren'],last=['Clover','Birch','Pebble','Maple','Meadow','River','Willow','Cloud','Moss','Fern','Brook','Reed','Hazel','Pine','Woods','Lake','Grove','Vale','Bloom','Sprout','Dawn','Stone','Briar','Skye','Cedar','Aster','Sparrow','Finch','Wilder','Rain','Cove','Marsh','Indigo','Sunny','Oak','Ember','Haven','Linden','Frost','Summer','Winter','Cricket','Laurel','Thistle','Bluebell','Saffron','Moon','Plum'];let name;do{const v=crypto.getRandomValues(new Uint32Array(2));name=`${first[v[0]%first.length]} ${last[v[1]%last.length]}`}while(name===previous);return name}
export function makeDefault(){return {seed:randomName(),options:{traits:{},background:false},material:{preset:'resin'},status:'none',badge:0,render:{transparent:true,resolution:768,samples:64}}}
export function loadSession(){try{const saved=JSON.parse(sessionStorage.getItem('blobatar-session')||'null');if(!saved?.config)return null;const c=saved.config;c.options??={};c.options.background=false;c.options.traits??={};c.render={transparent:true,resolution:768,samples:64,...c.render};c.material??={preset:'resin'};if(c.material.preset==='fur'&&c.material.furLength===.075&&c.material.furDensity===12000){c.material.furLength=.22;c.material.furDensity=28000}if(c.material.preset==='ceramic')c.material={...c.material,preset:'clay'};if(!MATERIAL_LABELS[c.material.preset])c.material={...c.material,preset:'resin'};if(c.seed==='alain00'&&!Object.keys(c.options.traits).length&&!Object.keys(c.options.palette??{}).length&&!c.options.hue&&!c.options.tone&&(!c.options.expression||c.options.expression==='idle')&&c.material.preset==='resin'&&(!c.status||c.status==='none')&&!c.badge)c.seed=randomName();return saved}catch{return null}}
export async function api(url,body,signal){const response=await fetch(url,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal});const text=await response.text();let result;try{result=JSON.parse(text)}catch{throw new Error(`Server request failed (${response.status}). Please try again shortly.`)}if(!response.ok)throw new Error(result.error||result.message||'Request failed');return result}
export function seededRandom(seed){let h=2166136261;for(const c of seed){h^=c.codePointAt(0);h=Math.imul(h,16777619)}return()=>{h+=0x6d2b79f5;let t=h;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
export function shuffleAvatar(config,locks,expressions,defaults){const next=clone(config),seed=randomName(config.seed),random=seededRandom(seed),pick=(list,old)=>{const choices=list.filter(v=>v!==old);return choices[Math.floor(random()*choices.length)]};next.seed=seed;if(!locks.material){const preset=pick(Object.keys(MATERIAL_LABELS),next.material.preset),d=defaults[preset];next.material={preset,roughness:round(Math.max(0,Math.min(1,d.roughness+(random()-.5)*.08))),textureScale:round(d.textureScale*(.8+random()*.4)),textureStrength:round(Math.min(1,d.textureStrength*(.8+random()*.4)))};if(preset==='fur'){next.material.furLength=round(.18+random()*.09);next.material.furDensity=24000+Math.floor(random()*80)*100}}if(!locks.color){const eye=next.options.palette?.eye,pinned=next.options.traits?.hue!==undefined||next.options.traits?.tone!==undefined||next.options.hue!==undefined||next.options.tone!==undefined;const head=pinned?undefined:pick(COLORS.map(([hex])=>hex),next.options.palette?.head);next.options.palette={...(head?{head}:{}),...(eye?{eye}:{})};if(!Object.keys(next.options.palette).length)delete next.options.palette}if(!locks.expression)next.options.expression=pick(expressions,next.options.expression??'idle');if(!locks.presence){next.status=pick(['none','online','away','offline','thinking'],next.status);next.badge=random()<.7?0:1+Math.floor(random()*128)}return next}
export function download(blob,name){const url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
