import {createPreview} from './preview.js';
import {recordAnimation} from './animation-export.js';
const $=id=>document.getElementById(id), copy=v=>structuredClone(v), round=v=>Math.round(v*1000)/1000;
const initial={seed:randomName(''),options:{traits:{},background:false},material:{preset:'resin'},status:'none',badge:0,render:{transparent:true,resolution:768,samples:64}};
let config=copy(initial),catalog,resolved,traitValues={},requestId=0,timer,rendering=false,theme=document.documentElement.dataset.theme;
let burstToken=0,burstTimer,burstExpression,thumbnailMap=new Map(),shapePool=false,locks={material:false,color:false,expression:false,presence:false},thumbnailService,thumbnailEpoch=0,thumbnailTimer,thumbnailSignature='',thumbnailQueue=Promise.resolve(),thumbnailCache=new Map();
const mainPreview=createPreview($('preview'));let logoPreview,logoConfig;
mainPreview.setTheme(theme);mainPreview.setMotion('hover');mainPreview.setGaze?.(true);mainPreview.setDraggable?.(true);mainPreview.setInteractionMode?.('rotate');
let materialDefaults={resin:{roughness:.22,textureScale:24,textureStrength:0},clay:{roughness:.78,textureScale:35,textureStrength:.045},fur:{roughness:.75,textureScale:30,textureStrength:.1,furLength:.075,furDensity:12000},jelly:{roughness:.30,textureScale:20,textureStrength:.015},glass:{roughness:.06,textureScale:24,textureStrength:0},chrome:{roughness:.16,textureScale:24,textureStrength:0},ceramic:{roughness:.38,textureScale:65,textureStrength:.05}};
const MATERIAL_LABELS={resin:'Resin',clay:'Clay',fur:'Fur',glass:'Glass'};
const BODY_COLORS=[['#15171A','Ink'],['#8F6146','Brown'],['#EF4444','Red'],['#F58D27','Orange'],['#EDBA30','Yellow'],['#3BCC94','Mint'],['#2CB9A6','Teal'],['#3693ED','Blue'],['#8955EF','Violet'],['#D753B1','Pink'],['#A6A7AE','Gray'],['#F1EEE9','Cream']];
const icons={round:'M30 4C48 4 57 15 56 32S45 57 28 56 4 43 4 27 13 4 30 4Z',organic:'M27 3C42 0 58 11 54 27S51 52 34 57 4 49 4 31 11 7 27 3Z',boxy:'M16 6H44Q54 6 54 16V44Q54 54 44 54H16Q6 54 6 44V16Q6 6 16 6',capsule:'M17 16H43C62 16 62 44 43 44H17C-2 44-2 16 17 16',nub:'M29 3C39-1 43 11 39 15C53 18 58 32 51 45C43 61 18 58 9 44C1 29 11 15 24 15C20 9 22 4 29 3',cloud:'M13 18C7 6 26 3 31 11C44 1 57 13 50 25C64 37 51 52 40 48C31 64 13 54 14 46C-2 45-3 25 13 18',droplet:'M30 3C23 13 6 27 7 39C8 61 52 61 53 39C54 27 37 13 30 3',hexagon:'M21 4Q30 0 39 6L53 16Q58 20 56 30L51 46Q49 53 39 55L22 56Q15 55 10 48L3 31Q1 24 7 17Z',sun:'M26 2H34L36 10L43 6L49 12L45 19L55 20L58 29L50 33L56 41L50 48L41 44L39 55L30 58L25 48L17 54L10 48L14 39L3 37L2 27L12 23L6 15L13 8L22 13Z',triangle:'M24 7Q30-2 36 7L56 43Q62 54 48 55H12Q-2 54 4 43Z'};
function shapeSvg(name){return `<svg viewBox="0 0 60 60" aria-hidden="true"><path d="${icons[name]||icons.round}"/><path d="M23 25v9M36 25v9" fill="none" stroke="var(--bg)" stroke-width="4" stroke-linecap="round"/></svg>`}
function el(tag,attrs={},text){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else n.setAttribute(k,v)}if(text!==undefined)n.textContent=text;return n}
function status(message,error=false){$('app-status').textContent=message;$('app-status').classList.toggle('error',error)}
async function api(url,body){const response=await fetch(url,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||result.message||'Request failed');return result}
function currentTraits(){return config.options.traits??={}}
function pinValue(key){return currentTraits()[key]}
function valueFor(key){const p=pinValue(key);return typeof p==='number'?p:(traitValues[key]??.5)}
function changed(rebuild=false){saveSession();cancelBurst();requestId++;syncExpression();updateReadbacks();clearTimeout(timer);timer=setTimeout(resolvePreview,50)}
async function resolvePreview(){const id=++requestId,snapshot=copy(config);try{const response=await api('/api/resolve',snapshot);if(id!==requestId)return;resolved=response.resolved??response;traitValues=response.traitValues??{};mainPreview.update(resolved);$('preview-loading').hidden=true;$('preview').classList.remove('preview-error');$('shape-caption').textContent=`Live preview · ${resolved.shape} · ${config.material.preset}`;$('preview').setAttribute('aria-label',`${config.material.preset} ${resolved.shape} avatar, seed ${config.seed}. Click to react.`);updateReadbacks();schedulePickerThumbnails();if(!rendering)status('');}catch(error){if(id===requestId){status(error.message,true);$('preview-loading').textContent=`Preview unavailable: ${error.message}`;$('preview-loading').hidden=false;$('preview').classList.add('preview-error')}}}
function activeShapes(){const p=pinValue('shape');if(Array.isArray(p))return catalog.shapes.filter(s=>p.includes(s.at)).map(s=>s.name);return [catalog.shapes.find(s=>s.at===p)?.name??resolved?.shape??'round']}
function applies(axis){return !axis.when||activeShapes().some(s=>axis.when.includes(s))}
function section(title,reset){const s=el('section',{class:'control-section'}),head=el('div',{class:'section-heading'});head.append(el('h2',{},title));if(reset){const b=el('button',{class:'auto-button',id:'auto-'+title.toLowerCase().replace(/[^a-z0-9]+/g,'-')},'Auto');b.onclick=reset;head.append(b)}s.append(head);return s}
function toggleCategory(key,value,order){if(key==='shape'&&!shapePool){currentTraits()[key]=value;changed(true);return}const p=pinValue(key),old=p===undefined?[]:Array.isArray(p)?p:[p];const chosen=order.filter(v=>v===value?!old.includes(v):old.includes(v));if(chosen.length)currentTraits()[key]=chosen.length===1?chosen[0]:chosen;else delete currentTraits()[key];if(key==='tone')delete config.options.tone;changed(true)}
function axisRow(axis){const key=axis.key,row=el('div',{class:'control-row','data-trait':key}),input=el('input',{type:'range',min:0,max:.999,step:.001,id:`trait-${key}`,'aria-label':`${axis.group} ${axis.label}`}),out=el('output',{for:`trait-${key}`}),pin=el('button',{class:'pin-button',id:`pin-${key}`,title:'Pin value','aria-label':`Pin ${key}`},'◇');row.append(el('label',{class:'control-label',for:input.id},axis.label),input,out,pin);input.value=valueFor(key);input.addEventListener('input',()=>{let v=Number(input.value);if(axis.bands)v=round((Math.min(axis.bands-1,Math.floor(v*axis.bands))+.5)/axis.bands);currentTraits()[key]=v;if(key==='hue')delete config.options.hue;if(key==='tone')delete config.options.tone;row.classList.add('pinned');out.value=v.toFixed(3);changed()});pin.onclick=()=>{if(pinValue(key)!==undefined)delete currentTraits()[key];else currentTraits()[key]=round(valueFor(key));changed(true)};return row}
function selectRow(label,values,value,change){const row=el('label',{class:'select-row'}),select=el('select',{'aria-label':label,id:'select-'+label.toLowerCase().replace(/[^a-z0-9]+/g,'-')});row.append(el('span',{},label));for(const item of values){const val=typeof item==='string'?item:item.value,text=typeof item==='string'?item:item.label;const option=el('option',{value:val},text);option.selected=val===value;select.append(option)}select.onchange=()=>change(select.value);row.append(select);return row}
function materialRow(label,key,min,max,step){const row=el('div',{class:'control-row','data-material':key}),input=el('input',{type:'range',min,max,step,id:`material-${key}`,'aria-label':label}),out=el('output');input.value=config.material[key]??materialDefaults[config.material.preset][key]??min;out.value=formatMaterial(key,Number(input.value));row.append(el('span',{class:'control-label'},label),input,out,el('span'));input.oninput=()=>{config.material[key]=Number(input.value);out.value=formatMaterial(key,Number(input.value));changed()};return row}
function formatMaterial(key,v){return key==='furDensity'?`${Math.round(v/1000)}k`:v>=10?String(Math.round(v)):v.toFixed(2)}
function renderControls(){if(!catalog)return;const ui=captureControlState(),controls=$('controls');controls.replaceChildren();const shape=section('Shape'),grid=el('div',{class:'shape-grid'});const auto=el('button',{class:`shape-option ${pinValue('shape')===undefined?'selected':''}`,'aria-pressed':pinValue('shape')===undefined},'');auto.id='shape-auto';auto.append(thumbnail('shape','round'),el('span',{},'Auto'));auto.onclick=()=>{delete currentTraits().shape;changed(true)};grid.append(auto);for(const s of catalog.shapes){const p=pinValue('shape'),selected=Array.isArray(p)?p.includes(s.at):p===s.at,b=el('button',{class:`shape-option ${selected?'selected':''}`,'aria-pressed':selected,id:`shape-${s.name}`,title:`Choose ${s.name}`});b.append(thumbnail('shape',s.name),el('span',{},s.name));b.onclick=()=>toggleCategory('shape',s.at,catalog.shapes.map(s=>s.at));grid.append(b)}shape.append(grid,el('p',{class:'hint'},shapePool?'Pick a few shapes for your shuffle pool.':'Pick one shape. Auto chooses from the name.'));controls.append(shape);
for(const group of ['body','eyes','color','decoration']){const axes=catalog.axes.filter(a=>a.group===group&&a.kind==='slider');if(!axes.length&&group!=='color')continue;const s=section(group[0].toUpperCase()+group.slice(1),()=>{for(const a of catalog.axes.filter(a=>a.group===group))delete currentTraits()[a.key];if(group==='color'){delete config.options.hue;delete config.options.tone;delete config.options.palette}changed(true)});s.dataset.group=group;if(group==='color'){const row=el('div',{class:'tone-row'});row.append(el('span',{},'tone'));const swatches=el('div',{class:'swatches'}),colors=['#cde0c2','#b1c69e','#899f72','#5e7650','#a9d976','#2e3e26'];catalog.tones.forEach((tone,i)=>{const p=pinValue('tone'),selected=Array.isArray(p)?p.includes(tone.at):p===tone.at,b=el('button',{class:`swatch ${selected?'selected':''}`,title:tone.name,id:`tone-${tone.name}`,'aria-label':`${tone.name} tone`,'aria-pressed':selected});b.style.background=colors[i];b.onclick=()=>toggleCategory('tone',tone.at,catalog.tones.map(t=>t.at));swatches.append(b)});row.append(swatches);s.append(row)}for(const axis of axes)s.append(axisRow(axis));if(group==='color'){const fields=el('div',{class:'color-fields'});for(const[key,label]of[['head','Body color'],['eye','Eye color']]){const l=el('label',{class:'color-field'}),input=el('input',{type:'color',id:`palette-${key}`,'aria-label':label,'data-palette':key});input.value=config.options.palette?.[key]??resolved?.colors?.[key]??(key==='head'?'#a3d8b0':'#10251a');input.oninput=()=>{(config.options.palette??={})[key]=input.value;changed()};l.append(input,el('span',{},label));fields.append(l)}s.append(fields);const resetColors=el('button',{class:'palette-reset'},'Use seeded colors');resetColors.onclick=()=>{delete config.options.palette;changed(true)};s.append(resetColors,el('p',{class:'hint'},'Custom colors replace the seeded palette.'))}controls.append(s)}
const material=section('Material');material.classList.add('material-section');const buttons=el('div',{class:'material-options'});for(const[preset,label]of Object.entries(MATERIAL_LABELS)){const b=el('button',{class:`material-option ${config.material.preset===preset?'selected':''}`,'aria-pressed':config.material.preset===preset},label);b.onclick=()=>{config.material={preset};changed(true)};buttons.append(b)}material.append(buttons,materialRow('Roughness','roughness',0,1,.01),materialRow('Texture scale','textureScale',.1,100,.1),materialRow('Texture strength','textureStrength',0,1,.005));material.append(materialRow('Fur length','furLength',.001,.3,.001),materialRow('Fur density','furDensity',100,50000,100));controls.insertBefore(material,controls.children[1]??null);
const features=section('Presence & backdrop');features.append(selectRow('Backdrop',[{value:'none',label:'None'},{value:'square',label:'Square'},{value:'circle',label:'Circle'},{value:'squircle',label:'Squircle'}],config.options.background===false||config.options.background===undefined?'none':config.options.background===true?'square':config.options.background,v=>{config.options.background=v==='none'?false:v;changed()}),selectRow('Status',['none','online','away','offline','thinking'],config.status,v=>{config.status=v;if(v==='thinking')config.options.expression='thinking';changed(true)}));const unread=el('label',{class:'select-row'}),count=el('input',{type:'number',min:0,max:999999,step:1,id:'unread-count',value:config.badge??0,'aria-label':'Unread count'});count.onchange=()=>{config.badge=Math.max(0,Math.trunc(Number(count.value)||0));count.value=config.badge;changed()};unread.append(el('span',{},'Unread count'),count);features.append(unread);controls.append(features);
const advanced=el('details',{class:'advanced-details'});advanced.append(el('summary',{},'More traits'));for(const axis of catalog.advancedControls??[])advanced.append(axisRow(axis));advanced.append(el('p',{class:'hint'},'Pinned traits stay fixed when you shuffle.'));controls.append(advanced);compactInspector();updateReadbacks();restoreControlState(ui)}
function updateReadbacks(){
 if(!catalog||!$('shape-auto'))return;const traits=currentTraits(),shapePin=traits.shape;const mark=(node,selected)=>{if(!node)return;node.classList.toggle('selected',selected);node.setAttribute('aria-pressed',String(selected))};
 mark($('shape-auto'),shapePin===undefined);for(const s of catalog.shapes)mark($(`shape-${s.name}`),Array.isArray(shapePin)?shapePin.includes(s.at):shapePin===s.at);
 for(const preset of Object.keys(MATERIAL_LABELS))mark($(`material-preset-${preset}`),config.material.preset===preset);
 for(const [hex,name]of BODY_COLORS)mark($(`color-${name.toLowerCase()}`),config.options.palette?.head===hex);
 for(const tone of catalog.tones)mark($(`tone-${tone.name}`),Array.isArray(traits.tone)?traits.tone.includes(tone.at):traits.tone===tone.at);
 const hint=$('shape-auto').closest('.control-section').querySelector('.hint');if(hint)hint.textContent=shapePool?'Pick a few shapes for your shuffle pool.':'Pick one shape. Auto chooses from the name.';
 if($('shape-pool-toggle'))$('shape-pool-toggle').checked=shapePool;for(const key of Object.keys(locks))if($(`lock-${key}`))$(`lock-${key}`).checked=locks[key];
 for(const row of document.querySelectorAll('[data-trait]')){const key=row.dataset.trait,axis=[...catalog.axes,...(catalog.advancedControls??[])].find(a=>a.key===key);row.hidden=!!axis&&!applies(axis);const pinned=pinValue(key)!==undefined,value=valueFor(key);row.classList.toggle('pinned',pinned);const input=row.querySelector('input');if(document.activeElement!==input)input.value=value;row.querySelector('output').value=value.toFixed(3);const button=row.querySelector('button');button.textContent=pinned?'◆':'◇';button.title=`${pinned?'Unpin':'Pin'} ${key}`;button.setAttribute('aria-label',button.title)}
 const decorations=document.querySelector('[data-group="decoration"]');if(decorations)decorations.hidden=![...decorations.querySelectorAll('[data-trait]')].some(row=>!row.hidden);
 for(const row of document.querySelectorAll('[data-material]')){const key=row.dataset.material;row.hidden=key.startsWith('fur')&&config.material.preset!=='fur';const input=row.querySelector('input'),value=config.material[key]??materialDefaults[config.material.preset]?.[key]??Number(input.min);if(document.activeElement!==input)input.value=value;row.querySelector('output').value=formatMaterial(key,value)}
 for(const input of document.querySelectorAll('[data-palette]'))if(document.activeElement!==input){const value=config.options.palette?.[input.dataset.palette]??resolved?.colors?.[input.dataset.palette];if(value)input.value=value}
 if($('select-status'))$('select-status').value=config.status??'none';if($('select-backdrop'))$('select-backdrop').value=!config.options.background?'none':config.options.background===true?'square':config.options.background;if($('unread-count')&&document.activeElement!==$('unread-count'))$('unread-count').value=config.badge??0;
 syncExpression();
}
function thumbnail(kind,name){const key=`${kind}:${name}`,img=el('img',{alt:'','data-thumbnail':key,width:64,height:64});img.src=thumbnailMap.get(key)??'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7';if(!thumbnailMap.has(key))img.classList.add('thumbnail-loading');return img}
function lockControl(section,key){const label=el('label',{class:'section-lock'}),input=el('input',{type:'checkbox',id:`lock-${key}`,'aria-label':`Lock ${key} when shuffling`});input.checked=locks[key];input.onchange=()=>{locks[key]=input.checked;saveSession()};label.append(input,el('span',{},'Lock'));section.querySelector('.section-heading').append(label)}
function captureControlState(){const active=document.activeElement;return {open:[...document.querySelectorAll('#controls details')].filter(d=>d.open).map(d=>d.querySelector('summary')?.textContent),scroll:document.querySelector('.inspector').scrollTop,focus:active?.id,selection:active?.selectionStart!==undefined?[active.selectionStart,active.selectionEnd]:null}}
function restoreControlState(ui){for(const d of document.querySelectorAll('#controls details'))d.open=ui.open.includes(d.querySelector('summary')?.textContent);const focus=ui.focus&&$(ui.focus);if(focus){focus.focus({preventScroll:true});if(ui.selection&&focus.setSelectionRange){try{focus.setSelectionRange(...ui.selection)}catch{}}}document.querySelector('.inspector').scrollTop=ui.scroll}
function compactInspector(){
 const controls=$('controls'),shape=controls.children[0],material=controls.querySelector('.material-section');
 if(material){lockControl(material,'material');for(const [i,preset]of Object.keys(MATERIAL_LABELS).entries()){const b=material.querySelectorAll('.material-option')[i];b.replaceChildren(thumbnail('material',preset),el('span',{},MATERIAL_LABELS[preset]));b.id=`material-preset-${preset}`}const texture=el('details',{class:'texture-details'});texture.append(el('summary',{},'Texture options'));for(const row of [...material.querySelectorAll('.control-row')])texture.append(row);material.append(texture);controls.prepend(material)}
 const expressionsSection=section('Expression'),grid=el('div',{class:'expression-grid'});lockControl(expressionsSection,'expression');
 for(const name of catalog.expressions){const b=el('button',{class:'expression-option',id:`expression-${name}`,'data-expression':name,'aria-pressed':(config.options.expression??'idle')===name,title:`Set ${name} expression`});b.append(thumbnail('expression',name),el('span',{},name));b.onclick=()=>chooseExpression(name);grid.append(b)}
 expressionsSection.append(grid);controls.insertBefore(expressionsSection,shape.nextSibling);
 const color=section('Color'),swatches=el('div',{class:'body-swatches'});lockControl(color,'color');
 for(const [hex,name]of BODY_COLORS){const b=el('button',{class:'body-swatch',id:`color-${name.toLowerCase()}`,title:name,'aria-label':`${name} body color`,'aria-pressed':config.options.palette?.head===hex});b.style.background=hex;if(config.options.palette?.head===hex)b.classList.add('selected');b.onclick=()=>{(config.options.palette??={}).head=hex;changed(true)};swatches.append(b)}
 const seeded=el('button',{class:'palette-reset'},'Use seeded colors');seeded.onclick=()=>{delete config.options.palette;changed(true)};const eyeAuto=el('button',{class:'palette-reset eye-auto',id:'eye-color-auto'},'Auto eye color');eyeAuto.onclick=()=>{if(config.options.palette)delete config.options.palette.eye;changed(true)};color.append(swatches,seeded,eyeAuto);controls.insertBefore(color,expressionsSection.nextSibling);
 const advanced=el('details',{class:'inspector-advanced'});advanced.append(el('summary',{},'Fine-tune your avatar'));
 const poolLabel=el('label',{class:'pool-toggle'}),pool=el('input',{type:'checkbox',id:'shape-pool-toggle'});pool.checked=shapePool;pool.onchange=()=>{shapePool=pool.checked;if(!shapePool&&Array.isArray(pinValue('shape'))){const choice=catalog.shapes.find(s=>s.name===resolved?.shape&&pinValue('shape').includes(s.at));currentTraits().shape=choice?.at??pinValue('shape')[0]}changed(true)};poolLabel.append(pool,el('span',{},'Choose multiple shapes for shuffle'));advanced.append(poolLabel);
 for(const node of [...controls.children])if(node.dataset.group||node.classList.contains('advanced-details')||node.querySelector('h2')?.textContent==='Presence & backdrop'){if(node.querySelector('h2')?.textContent==='Presence & backdrop')lockControl(node,'presence');advanced.append(node)}
 controls.append(advanced);syncExpression();
}
function schedulePickerThumbnails(){
 if(!resolved||!catalog)return;
 const palette={head:(resolved.motion?.baseColors??resolved.colors).head,eye:(resolved.motion?.baseColors??resolved.colors).eye},material=copy(resolved.material??config.material),shape=catalog.shapes.find(s=>s.name===resolved.shape)?.at??.11;
 const signature=JSON.stringify({palette,material,shape});if(signature===thumbnailSignature)return;thumbnailSignature=signature;
 const token=++thumbnailEpoch;clearTimeout(thumbnailTimer);thumbnailTimer=setTimeout(()=>{thumbnailQueue=thumbnailQueue.then(()=>loadPickerThumbnails({palette,material,shape},token)).catch(error=>console.warn('Thumbnail refresh failed',error.message))},180);
}
async function loadPickerThumbnails(context,token){
 if(token!==thumbnailEpoch)return;
 try{const module=await import('./preview.js');thumbnailService=module.createThumbnailRenderer();
 const jobs=[...Object.keys(MATERIAL_LABELS).map(preset=>({key:`material:${preset}`,shape:context.shape,expression:'idle',material:preset===context.material.preset?context.material:{preset}})),...catalog.shapes.map(s=>({key:`shape:${s.name}`,shape:s.at,expression:'idle',material:context.material})),...catalog.expressions.map(expression=>({key:`expression:${expression}`,shape:context.shape,expression,material:context.material}))],batch=new Map();
 for(const job of jobs){if(token!==thumbnailEpoch)return;const input={seed:'picker-study',options:{traits:{shape:job.shape,'eye.ratio':.8},palette:context.palette,background:false,expression:job.expression},material:job.material},key=JSON.stringify(input);
 let uri=thumbnailCache.get(key);if(!uri){const response=await api('/api/resolve',input);if(token!==thumbnailEpoch)return;uri=await thumbnailService.render(response.resolved??response,{size:112});thumbnailCache.set(key,uri);while(thumbnailCache.size>135)thumbnailCache.delete(thumbnailCache.keys().next().value)}batch.set(job.key,uri);await new Promise(r=>setTimeout(r,0))}
 // Decode the complete next set off-DOM. Keep the last valid set visible until this commit.
 await Promise.all([...batch.values()].map(async uri=>{const image=new Image();image.src=uri;await image.decode()}));if(token!==thumbnailEpoch)return;
 thumbnailMap=batch;for(const image of document.querySelectorAll('[data-thumbnail]')){const uri=batch.get(image.dataset.thumbnail);if(uri){image.src=uri;image.classList.remove('thumbnail-loading');image.removeAttribute('aria-busy')}}
 }catch(error){if(token===thumbnailEpoch)thumbnailSignature='';console.warn('3D thumbnail batch unavailable',error.message)}finally{thumbnailService?.dispose?.();thumbnailService=undefined}
}
function cancelBurst(){burstToken++;clearTimeout(burstTimer);burstExpression=undefined}
async function react(){if(!catalog)return;clearTimeout(burstTimer);const token=++burstToken;requestId++;clearTimeout(timer);const current=burstExpression??config.options.expression??'idle',choices=catalog.expressions.filter(e=>e!=='idle'&&e!==current),expression=choices[crypto.getRandomValues(new Uint32Array(1))[0]%choices.length];burstExpression=expression;try{const response=await api('/api/resolve',{...copy(config),options:{...copy(config.options),expression}});if(token!==burstToken)return;mainPreview.update(response.resolved??response);$('shape-caption').textContent=`Reaction · ${expression}`;burstTimer=setTimeout(()=>{if(token!==burstToken)return;burstExpression=undefined;resolvePreview()},1500)}catch(error){if(token===burstToken){status(error.message,true);resolvePreview()}}}
$('preview').onclick=e=>{if(!e.defaultPrevented)react()};$('preview').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();react()}};
$('gaze-visible').onchange=()=>{$('gaze-toggle').checked=$('gaze-visible').checked;mainPreview.setGaze?.($('gaze-visible').checked);saveSession();};

function syncExpression(){const current=config.options.expression??'idle';$('expression-main').value=current;for(const b of document.querySelectorAll('[data-expression]')){const active=b.dataset.expression===current;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',active)}}
function chooseExpression(value){config.options.expression=value;changed();}
$('expression-main').onchange=()=>chooseExpression($('expression-main').value);
$('gaze-toggle').onchange=()=>{mainPreview.setGaze?.($('gaze-toggle').checked);saveSession();};
function buildExpressionControls(){const select=$('expression-main');select.replaceChildren();for(const expression of catalog.expressions)select.append(el('option',{value:expression},expression[0].toUpperCase()+expression.slice(1)));const row=$('expression-shortcuts');row.replaceChildren();for(const[name,symbol]of[['happy','⌣'],['sad','⌢'],['wink','◠'],['mad','⌁'],['thinking','···']]){const b=el('button',{'data-expression':name,'aria-pressed':false,title:`Set ${name} expression`});b.append(el('span',{'aria-hidden':true,class:'expression-symbol'},symbol),el('span',{},name[0].toUpperCase()+name.slice(1)));b.onclick=()=>chooseExpression(name);row.append(b)}syncExpression()}

function seedRandom(seed){let h=2166136261;for(const char of seed){h^=char.codePointAt(0);h=Math.imul(h,16777619)}return()=>{h+=0x6d2b79f5;let t=h;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}
async function initLogo(){
 let previous={};try{previous=JSON.parse(sessionStorage.getItem('squish-logo-look')||'{}')}catch{}
 let seed;do{seed=randomName()}while(seed===previous.seed);const random=seedRandom(seed),colors=BODY_COLORS.filter(([hex])=>hex!==previous.color),color=colors[Math.floor(random()*colors.length)][0],preset=Object.keys(MATERIAL_LABELS)[Math.floor(random()*Object.keys(MATERIAL_LABELS).length)];
 const attempts=[{seed,options:{traits:{'body.r':.8},palette:{head:color},background:false},material:{preset}},{seed,options:{traits:{shape:.11,'body.r':.8,'eye.ratio':.8},palette:{head:color},background:false},material:{preset:'resin'}}];
 for(const input of attempts){try{const response=await api('/api/resolve',input),scene=response.resolved??response;logoPreview?.destroy?.();logoPreview=createPreview($('brand-avatar'));logoPreview.setTheme(theme);logoPreview.setMotion('always');logoPreview.setGaze?.(false);logoPreview.setDraggable?.(false);logoPreview.update(scene);logoConfig=copy(scene.config);$('brand-avatar').classList.add('logo-ready');try{sessionStorage.setItem('squish-logo-look',JSON.stringify({seed,color}))}catch{}return}catch(error){logoPreview?.destroy?.();logoPreview=undefined;console.warn('Header avatar fallback',error.message)}}
}
function randomName(previous=config.seed){const first=['Milo','Luna','Oliver','Sage','Noah','Zoe','Finn','Ada','Theo','Iris','Arlo','Nora','Leo','Ruby','Remy','Maya','Jude','Cleo','Eli','Nova','Luca','Esme','Owen','Alma','Felix','Wren','Ezra','Pearl','Oscar','June','Rory','Isla','Hugo','Olive','Beau','Cora','Ari','Vera','Nico','Flora','Otis','Lyra','Kit','Maeve','Levi','Nell','Rio','Faye','Asa','Mabel','Enzo','Mira','Ivo','Daisy','Micah','Tess','Jasper','Lila','Basil','Thea','Rowan','Elio','Anya','Soren'],last=['Clover','Birch','Pebble','Maple','Meadow','River','Willow','Cloud','Moss','Fern','Brook','Reed','Hazel','Pine','Woods','Lake','Grove','Vale','Bloom','Sprout','Dawn','Stone','Briar','Skye','Cedar','Aster','Sparrow','Finch','Wilder','Rain','Cove','Marsh','Indigo','Sunny','Oak','Ember','Haven','Linden','Frost','Summer','Winter','Cricket','Laurel','Thistle','Bluebell','Saffron','Moon','Plum'];let name;do{const v=crypto.getRandomValues(new Uint32Array(2));name=`${first[v[0]%first.length]} ${last[v[1]%last.length]}`}while(name===previous);return name}
document.querySelector('.brand').onclick=event=>{event.preventDefault();if(!logoConfig)return;config={...copy(logoConfig),render:copy(config.render)};locks={material:false,color:false,expression:false,presence:false};shapePool=Array.isArray(config.options.traits?.shape);syncForm();changed(true);status('Editing the header SquishBot.')};
function syncInteractionMode(){const mode=$('interaction-mode').value;mainPreview.setInteractionMode?.(mode);document.querySelector('.interaction-cue').textContent=mode==='rotate'?'Drag to rotate. Switch to Play to move and bounce.':'Move your pointer. Click to react. Drag to play.'}
$('interaction-mode').onchange=()=>{syncInteractionMode();saveSession()};$('reset-view').onclick=()=>mainPreview.resetView?.();
function shuffleAvatar(){
 const seed=randomName(),random=seedRandom(seed),pick=(values,previous)=>{const choices=values.filter(v=>v!==previous);return choices[Math.floor(random()*choices.length)]};
 config.seed=seed;
 if(!locks.material){const preset=pick(Object.keys(MATERIAL_LABELS),config.material.preset);config.material={preset,roughness:round(Math.min(1,Math.max(0,materialDefaults[preset].roughness+(random()-.5)*.08))),textureScale:round(materialDefaults[preset].textureScale*(.8+random()*.4)),textureStrength:round(Math.min(1,materialDefaults[preset].textureStrength*(.8+random()*.4)))};if(preset==='fur'){config.material.furLength=round(.05+random()*.05);config.material.furDensity=8000+Math.floor(random()*100)*100}}
 if(!locks.color){const eye=config.options.palette?.eye;const colorPinned=pinValue('hue')!==undefined||pinValue('tone')!==undefined||config.options.hue!==undefined||config.options.tone!==undefined;if(colorPinned){config.options.palette=eye?{eye}:undefined}else{const head=pick(BODY_COLORS.map(([hex])=>hex),config.options.palette?.head);config.options.palette=eye?{head,eye}:{head}}}
 if(!locks.expression)config.options.expression=pick(catalog.expressions,config.options.expression??'idle');
 if(!locks.presence){config.status=pick(['none','online','away','offline','thinking'],config.status);config.badge=random()<.7?0:1+Math.floor(random()*128)}
 syncForm();changed(true);
}
function saveSession(){try{sessionStorage.setItem('blobatar-session',JSON.stringify({config,locks,shapePool,interactionMode:$('interaction-mode').value,motion:$('motion').value,gaze:$('gaze-visible').checked}))}catch{}}
function download(content,name,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type}));const a=el('a',{href:url,download:name});a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function syncForm(){syncExpression();$('seed').value=config.seed;$('transparent').checked=config.render.transparent;$('export-size').value=String(config.render.resolution)}
$('seed').oninput=()=>{config.seed=$('seed').value;changed()};$('shuffle').onclick=shuffleAvatar;$('reset-all').onclick=()=>{config=copy(initial);locks={material:false,color:false,expression:false,presence:false};shapePool=false;syncForm();changed(true)};$('motion').onchange=()=>{mainPreview.setMotion($('motion').value);saveSession();};$('theme-toggle').onclick=()=>{theme=theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('squish-theme',theme)}catch{}mainPreview.setTheme(theme);logoPreview?.setTheme(theme);$('theme-toggle').setAttribute('aria-label',`Switch to ${theme==='dark'?'light':'dark'} mode`);};$('transparent').onchange=()=>{config.render.transparent=$('transparent').checked;changed()};$('export-size').onchange=()=>{config.render.resolution=Number($('export-size').value);changed()};
$('export-format').onchange=()=>{const format=$('export-format').value,animated=format!=='png';$('render-button').textContent=`Export ${format.toUpperCase()} ↗`;$('animation-note').hidden=!animated;$('transparent').disabled=animated;$('export-size').disabled=animated};
$('render-button').onclick=async()=>{const button=$('render-button'),snapshot=copy(config),format=$('export-format').value;if(format!=='png'){button.disabled=true;rendering=true;try{mainPreview.setMotion('always');const result=await recordAnimation($('preview').querySelector('canvas'),format,{onProgress:message=>status(message),background:theme==='dark'?'#141820':'#f8f8fc'});download(result.blob,`squishbots.${result.extension}`,result.blob.type);status(`${format.toUpperCase()} downloaded. Recorded from the live preview.`)}catch(error){status(error.message,true)}finally{mainPreview.setMotion($('motion').value);button.disabled=false;rendering=false}return}button.disabled=true;rendering=true;status('Rendering your PNG in Blender…');$('render-result').hidden=true;try{const job=await api('/api/render',snapshot);let result=job;while(!['complete','completed','done','failed','error','cancelled'].includes(result.status)){await new Promise(r=>setTimeout(r,800));result=await api(`/api/jobs/${job.id}`)}if(['failed','error','cancelled'].includes(result.status))throw new Error(result.error||'Blender render failed');const url=result.result?.png??result.result?.url??result.resultUrl??result.url??result.urls?.png??result.png;const area=$('render-result');area.replaceChildren();if(url){const img=el('img',{src:url,alt:'Final Blender render'}),link=el('a',{href:url,download:'squishbots.png'},'Download PNG');area.append(img,link)}else area.append(el('span',{},'Render complete.'));area.hidden=false;status(JSON.stringify(snapshot)===JSON.stringify(config)?'Your Blender render is ready.':'Your earlier configuration is ready. Export again for your latest changes.')}catch(error){status(error.message,true)}finally{button.disabled=false;rendering=false}};
async function init(){$('theme-toggle').setAttribute('aria-label',`Switch to ${theme==='dark'?'light':'dark'} mode`);try{catalog=await api('/api/catalog');materialDefaults=catalog.materialDefaults??materialDefaults;initLogo();try{const saved=JSON.parse(sessionStorage.getItem('blobatar-session')||'null');if(saved?.config){if(['jelly','chrome'].includes(saved.config.material?.preset))saved.config.material={preset:'resin'};if(['wool','velvet','foam','ceramic'].includes(saved.config.material?.preset))saved.config.material={...saved.config.material,preset:'clay'};await api('/api/resolve',saved.config);config={...copy(initial),...saved.config,options:{...initial.options,...saved.config.options},material:{preset:'resin',...saved.config.material},render:{...initial.render,...saved.config.render}};if(config.seed==='alain00'&&Object.keys(config.options.traits??{}).length===0&&Object.keys(config.options.palette??{}).length===0&&!config.options.hue&&!config.options.tone&&(!config.options.expression||config.options.expression==='idle')&&config.material.preset==='resin'&&(!config.status||config.status==='none')&&!config.badge)config.seed=initial.seed;if(saved.locks)for(const key of Object.keys(locks))locks[key]=saved.locks[key]===true;shapePool=saved.shapePool===true||Array.isArray(config.options.traits?.shape);if(['rotate','play'].includes(saved.interactionMode))$('interaction-mode').value=saved.interactionMode;syncInteractionMode();if(['none','hover','always'].includes(saved.motion))$('motion').value=saved.motion;if(typeof saved.gaze==='boolean'){$('gaze-visible').checked=saved.gaze;$('gaze-toggle').checked=saved.gaze}mainPreview.setMotion($('motion').value);mainPreview.setGaze?.($('gaze-visible').checked)}}catch{}buildExpressionControls();syncForm();renderControls();await resolvePreview()}catch(error){status(error.message,true);$('controls').textContent='Could not load the editor.'}}
init();
