import * as THREE from 'three';
import {createFurEye,updateFurEye,furEyeDimensions} from './fur-eyes.js';
import { resolveGeometry, bodyMeshData, eyeMeshData, pathPoints, deformEye, surfaceDepth } from './geometry.js';
import {naturalBlink,idleAt,project,step,pursuit,lerpPose,IDENT,MORPH_IN,MORPH_OUT} from './motion.js';

function studioEnvironment(){const studio=new THREE.Scene();studio.background=new THREE.Color().setRGB(.035,.04,.05);for(const [position,size,power] of [[[-3,4,3],[3,4],20],[[3,1,-2],[2,3],12],[[1,-1,4],[1.5,2],1.2]]){const panel=new THREE.Mesh(new THREE.PlaneGeometry(...size),new THREE.MeshBasicMaterial({color:new THREE.Color().setRGB(power,power,power),side:THREE.DoubleSide}));panel.position.set(...position);panel.lookAt(0,0,0);studio.add(panel)}return studio}
function seededRandom(){let n=0x6d2b79f5;return()=>{n|=0;n=n+0x6d2b79f5|0;let t=Math.imul(n^n>>>15,1|n);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function geometry(data){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(data.vertices,3));geo.setIndex(data.indices);if(data.normals)geo.setAttribute('normal',new THREE.Float32BufferAttribute(data.normals,3));else geo.computeVertexNormals();const uv=[];for(let i=0;i<data.vertices.length;i+=3)uv.push((data.vertices[i]+1.5)/3,(data.vertices[i+1]+1.5)/3);geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));return geo}
function grainTexture(scale){const n=128,data=new Uint8Array(n*n),rand=seededRandom();for(let i=0;i<data.length;i++)data[i]=Math.round(96+rand()*64);const texture=new THREE.DataTexture(data,n,n,THREE.RedFormat);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(scale/10,scale/10);texture.magFilter=THREE.LinearFilter;texture.minFilter=THREE.LinearMipmapLinearFilter;texture.generateMipmaps=true;texture.needsUpdate=true;return texture}
function bodyMaterial(resolved){const m=resolved.material??{},preset=m.preset??'resin',color=new THREE.Color(resolved.marks[0].fill),defaults={resin:.22,clay:.78,fur:.75,glass:.06},mat=new THREE.MeshPhysicalMaterial({color:preset==='glass'?new THREE.Color('#ffffff'):color,roughness:m.roughness??defaults[preset]??.22,metalness:0,ior:preset==='glass'?1.45:1.47,transmission:preset==='glass'?1:0,thickness:preset==='glass'?2*(resolved.render?.depth??.95):0,attenuationColor:color,attenuationDistance:preset==='glass'?3:Infinity,clearcoat:preset==='resin'?.32:0,clearcoatRoughness:.14,sheen:preset==='fur'?.28:.02,sheenRoughness:.8,sheenColor:color,envMapIntensity:.95});const strength=m.textureStrength??0;if(strength){mat.bumpMap=grainTexture(m.textureScale??35);mat.bumpScale=strength*.015}return mat}



function makeFur(geo,g,eyes,m,color){const random=seededRandom(),p=geo.attributes.position,n=geo.attributes.normal,indices=geo.index.array,triangles=[],cumulative=[];let total=0;const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3();for(let i=0;i<indices.length;i+=3){a.fromBufferAttribute(p,indices[i]);b.fromBufferAttribute(p,indices[i+1]);c.fromBufferAttribute(p,indices[i+2]);const area=new THREE.Vector3().subVectors(b,a).cross(new THREE.Vector3().subVectors(c,a)).length()/2;total+=area;triangles.push([indices[i],indices[i+1],indices[i+2]]);cumulative.push(total)}
 const verts=[],colors=[],normals=[],faces=[],length=m.furLength??.22,count=Math.min(m.furDensity??28000,40000);
 for(let i=0;i<count;i++){
  const seek=random()*total;let lo=0,hi=cumulative.length-1;while(lo<hi){const mid=(lo+hi)>>1;if(cumulative[mid]<seek)lo=mid+1;else hi=mid}
  const tri=triangles[lo],u=Math.sqrt(random()),v=random(),weights=[1-u,u*(1-v),u*v],pos=new THREE.Vector3(),normal=new THREE.Vector3();
  for(let j=0;j<3;j++){pos.addScaledVector(new THREE.Vector3().fromBufferAttribute(p,tri[j]),weights[j]);normal.addScaledVector(new THREE.Vector3().fromBufferAttribute(n,tri[j]),weights[j])}normal.normalize();
  // Nearby roots share a comb direction, with a little individual flyaway variation.
  const flow=new THREE.Vector3(.35*Math.sin(pos.y*9+pos.x*7),-1,.15*Math.sin(pos.x*8));flow.addScaledVector(normal,-flow.dot(normal)).normalize();
  const side=new THREE.Vector3().crossVectors(normal,flow).normalize(),h=length*(.75+random()*.75),curl=(random()-.5)*.3,shade=.82+random()*.18,width=.0035+random()*.002,offset=verts.length/3;
  for(let j=0;j<=6;j++){
   const t=j/6,tip=pos.clone().addScaledVector(normal,h*(t-.35*t*t)).addScaledVector(flow,h*1.15*t*t).addScaledVector(side,h*curl*Math.sin(t*Math.PI));
   const radius=width*Math.pow(1-t,.8)+.00004;
   for(const sign of [-1,1]){verts.push(...tip.clone().addScaledVector(side,radius*sign));normals.push(...normal);const light=shade*(.65+.35*Math.sqrt(t));colors.push(light,light,light)}
   if(j<6){const k=offset+j*2;faces.push(k,k+1,k+2,k+1,k+3,k+2)}
  }
 }
 const f=new THREE.BufferGeometry();f.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));f.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));f.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));f.setIndex(faces);const mat=new THREE.MeshStandardMaterial({color,vertexColors:true,roughness:.85,metalness:0,side:THREE.DoubleSide,envMapIntensity:.65});const fur=new THREE.Mesh(f,mat);fur.userData.maskPad=length;return fur;
}


function disposeGroup(group){group.traverse(o=>{o.geometry?.dispose();const ms=o.material?Array.isArray(o.material)?o.material:[o.material]:[];for(const m of ms){m.map?.dispose();m.bumpMap?.dispose();m.dispose()}})}

export function createPreview(container){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.AgXToneMapping;renderer.toneMappingExposure=1.12;renderer.setClearColor(0x000000,0);renderer.domElement.setAttribute('aria-label','Interactive 3D avatar preview');renderer.domElement.style.cssText='display:block;width:100%;height:100%;touch-action:pan-y';container.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-1.65,1.65,1.65,-1.65,.1,100);camera.position.set(0,0,8);const pmrem=new THREE.PMREMGenerator(renderer),room=studioEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;disposeGroup(room);pmrem.dispose();scene.add(new THREE.HemisphereLight(0xe8f4ff,0x52677c,.18));const key=new THREE.DirectionalLight(0xffffff,.4);key.position.set(-3,4,4);scene.add(key);const fill=new THREE.DirectionalLight(0xb9deff,.7);fill.position.set(3,1,-1);scene.add(fill);
 let blinkTimer=0,blinkAt=-Infinity;let freezeForCapture=false;let avatar=new THREE.Group(),motion='none',hover=false,theme='light',disposed=false,raf=0,epoch=performance.now(),last=0;
 let reaction=null,currentPose={...IDENT},fromPose=currentPose,toPose=currentPose,morphStart=0,morphTiming=MORPH_IN,colorFrom=null,colorTo=null;
 let interactionMode='rotate',viewYaw=0,viewPitch=0;const viewQuaternion=new THREE.Quaternion();let gazeEnabled=false,pointer=null,gazeX=0,gazeY=0,amp=0,lift=0;const drag={enabled:false,active:false,id:null,x:0,y:0,vx:0,vy:0,startX:0,startY:0,originX:0,originY:0,pushX:0,pushY:1,moved:false};let suppressClick=false,gesturePose={...IDENT},gestureMix=0,gestureKind=null,impactAt=-1e9,impactAxis='x',impactSign=1,releaseAt=-1e9;const raycaster=new THREE.Raycaster();const still=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover: hover) and (pointer: fine)');scene.add(avatar);
 function resize(){if(disposed)return;const w=Math.max(1,container.clientWidth),h=Math.max(1,container.clientHeight);renderer.setSize(w,h,false);const aspect=w/h,span=1.65;camera.left=-span*Math.max(1,aspect);camera.right=span*Math.max(1,aspect);camera.top=span*Math.max(1,1/aspect);camera.bottom=-camera.top;camera.updateProjectionMatrix();renderer.render(scene,camera)}
 const observer=new ResizeObserver(resize);observer.observe(container);resize();
 function armBlink(){clearTimeout(blinkTimer);if(disposed||still.matches||document.hidden)return;blinkTimer=setTimeout(()=>{blinkAt=performance.now();schedule();armBlink()},2800+Math.random()*3700)}
 function visibilityChange(){blinkAt=-Infinity;armBlink();schedule()}
 document.addEventListener('visibilitychange',visibilityChange);still.addEventListener('change',visibilityChange);armBlink();
 function schedule(){if(!disposed&&!raf)raf=requestAnimationFrame(animate)}
 function animate(now=performance.now()){
  raf=0;if(disposed)return;const dt=last?Math.min(64,now-last):16;last=now;const reduced=still.matches||freezeForCapture,active=!reduced&&(motion==='always'||motion==='hover'&&hover&&fine.matches),desiredAmp=active?1:0;
  amp+= (desiredAmp-amp)*(1-Math.exp(-dt/100));if(Math.abs(desiredAmp-amp)<.001)amp=desiredAmp;
  const wantedLift=!reduced&&hover&&fine.matches&&motion!=='none'?1:0;lift+=(wantedLift-lift)*(1-Math.exp(-dt/(wantedLift?55:40)));if(Math.abs(wantedLift-lift)<.001)lift=wantedLift;
  const canGaze=gazeEnabled&&fine.matches&&!reduced&&pointer;let movingGaze=false;
  if(canGaze){const r=container.getBoundingClientRect(),v=step({x:gazeX,y:gazeY,dx:pointer.x-r.left-r.width/2-drag.x*r.width/(camera.right-camera.left),dy:pointer.y-r.top-r.height/2+drag.y*r.height/(camera.top-camera.bottom),radius:Math.max(1,Math.min(r.width,r.height)/2),k:pursuit(dt,110),snap:1.6});gazeX=v.x;gazeY=v.y;movingGaze=Math.hypot(v.tx-gazeX,v.ty-gazeY)>.0005}
  else {const k=pursuit(dt,110);gazeX*=1-k;gazeY*=1-k;movingGaze=Math.hypot(gazeX,gazeY)>.0005;if(!movingGaze)gazeX=gazeY=0}
  if(reduced&&!drag.active)drag.x=drag.y=drag.vx=drag.vy=0;
  if(!drag.active&&(Math.hypot(drag.x,drag.y,drag.vx,drag.vy)>.0001)){const h=Math.min(dt,32)/1000;drag.vx+=(-180*drag.x-24*drag.vx)*h;drag.vy+=(-180*drag.y-24*drag.vy)*h;drag.x+=drag.vx*h;drag.y+=drag.vy*h;if(Math.hypot(drag.x,drag.y,drag.vx,drag.vy)<.001)drag.x=drag.y=drag.vx=drag.vy=0}
  const progress=reduced?1:Math.min(1,(now-morphStart)/morphTiming.ms),mix=morphTiming.ease(progress);currentPose=lerpPose(fromPose,toPose,mix);
  if(reaction){const {g,eyes,baseLayout,seeds,body,bodyColorTarget,eyeColorTarget}=reaction,seedFrame={...seeds};
   const impactAge=now-impactAt,impactLive=interactionMode==='play'&&impactAge<500,kind=impactLive?'edge':drag.active&&interactionMode==='play'?(drag.moved?'drag':'press'):null;gestureKind=kind??gestureKind;const wantedGesture=kind?1:0;gestureMix=reduced?wantedGesture:gestureMix+(wantedGesture-gestureMix)*(1-Math.exp(-dt/(wantedGesture?45:110)));if(Math.abs(wantedGesture-gestureMix)<.001)gestureMix=wantedGesture;if(kind&&reaction.reactionPoses?.[kind])gesturePose=lerpPose(gesturePose,reaction.reactionPoses[kind],reduced?1:1-Math.exp(-dt/55));const visiblePose=lerpPose(currentPose,gesturePose,gestureMix);
   // A pointer owns the eyes while present; the source idle glance stands down.
   if(canGaze)for(const k of ['lookX','lookY','lookMX','lookMY'])seedFrame[k]=0;
   const f=idleAt(seedFrame,now-epoch,amp,reduced?0:visiblePose.shake),face=baseLayout.face??baseLayout.body;
   f.blink=reduced?1:naturalBlink(now-blinkAt);if(reduced)f.rockp=1;
   const press=!reduced&&interactionMode==='play'&&drag.active&&!drag.moved?gestureMix:0,stretch=!reduced&&interactionMode==='play'&&drag.active&&drag.moved?gestureMix:0,impact=!reduced&&impactLive?Math.exp(-impactAge/150)*.22:0,releaseAge=(now-releaseAt)/1000,bounce=!reduced&&releaseAge<.7?Math.sin(releaseAge*18)*Math.exp(-releaseAge*7)*.07:0;let scaleX=1+.22*press-bounce,scaleY=1-.25*press+bounce;if(impactAxis==='x'){scaleX-=impact;scaleY+=impact*.6}else{scaleX+=impact*.6;scaleY-=impact}avatar.scale.set(f.breathe[0]*(1+.04*lift)*scaleX,f.breathe[1]*(1+.04*lift)*scaleY,1);avatar.position.set(f.shake[0]/32+drag.x,(-visiblePose.bdy-f.bob-f.shake[1]+1.5*lift)/32+drag.y-.035*press,0);if(interactionMode==='rotate')avatar.quaternion.copy(viewQuaternion);else{avatar.rotation.z=drag.x*-.08;avatar.rotation.y=drag.x*.12;}avatar.updateMatrix();avatar.matrixAutoUpdate=false;
   if(!reduced&&interactionMode==='play'){const amount=.30*stretch-bounce*2,nx=drag.pushX,ny=drag.pushY,along=1-amount,across=1+amount*.65;const deformation=new THREE.Matrix4().set(across+(along-across)*nx*nx,(along-across)*nx*ny,0,0,(along-across)*nx*ny,across+(along-across)*ny*ny,0,0,0,0,1,0,0,0,0,1);const position=avatar.position.clone();avatar.matrix.setPosition(0,0,0);avatar.matrix.premultiply(deformation);avatar.matrix.setPosition(position);avatar.matrixWorldNeedsUpdate=true;}

   for(let i=0;i<eyes.length;i++){const e=baseLayout.eyes[i],mark={x:(e.cx-face.cx)/face.rx,y:(e.cy-face.cy)/face.ry},projection=project(mark,gazeX*12/face.rx,gazeY*12/face.ry),item=eyes[i];if(item.furry){updateFurEye(item.furry,e,i,g,visiblePose,f,projection,face,bodyColorTarget);item.furry.group.position.x+=(g.cx-50)/32;item.furry.group.position.y+=(50-g.cy)/32;continue}deformEye(item.base,item.mesh.geometry.attributes.position.array,e,i,g,visiblePose,f,projection,face);item.mesh.geometry.attributes.position.needsUpdate=true;item.mesh.geometry.computeVertexNormals();item.mesh.material.color.copy(colorFrom?.eye??eyeColorTarget).lerp(eyeColorTarget,mix)}
   for(const brow of reaction.brows){const base=brow.userData.base,out=brow.geometry.attributes.position.array;for(let j=0;j<base.length;j+=3){const x=base[j]+gazeX*12/32,y=base[j+1]-gazeY*12/32;out[j]=x;out[j+1]=y;out[j+2]=surfaceDepth(x,y,g)+base[j+2]-surfaceDepth(base[j],base[j+1],g)}brow.geometry.attributes.position.needsUpdate=true;brow.geometry.computeVertexNormals();brow.material.color.copy(eyeColorTarget)}
   body.material.color.copy(colorFrom?.head??bodyColorTarget).lerp(bodyColorTarget,mix);
   // Expose observable interaction state for accessibility/debugging tests.
   renderer.domElement.dataset.blink=f.blink.toFixed(3);renderer.domElement.dataset.gaze=`${gazeX.toFixed(3)},${gazeY.toFixed(3)}`;renderer.domElement.dataset.expression=reaction.expression;renderer.domElement.dataset.view=`${viewYaw.toFixed(3)},${viewPitch.toFixed(3)}`;renderer.domElement.dataset.interaction=interactionMode;renderer.domElement.dataset.gesture=kind??(gestureMix>.01?'recovering':'none');renderer.domElement.dataset.edge=impactLive?impactAxis:'none';renderer.domElement.dataset.drag=`${drag.x.toFixed(3)},${drag.y.toFixed(3)}`;
  }
  renderer.render(scene,camera);if(!reduced&&now-blinkAt<190||gestureMix>.001||now-impactAt<500||now-releaseAt<700||drag.active||Math.hypot(drag.x,drag.y,drag.vx,drag.vy)>.001||active||amp!==desiredAmp||lift!==wantedLift||movingGaze||progress<1||!reduced&&reaction&&(currentPose.shake||currentPose.rock))schedule();else last=0;
 }
 const enter=()=>{hover=true;schedule()},leave=()=>{hover=false;schedule()},move=e=>{if(!gazeEnabled||!fine.matches||still.matches)return;pointer={x:e.clientX,y:e.clientY};schedule()},windowLeave=()=>{pointer=null;schedule()},mediaChange=()=>{if(still.matches){gazeX=gazeY=amp=lift=0}schedule()};
 function hitBody(x,y){if(!drag.enabled||!reaction)return false;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1),camera);return raycaster.intersectObject(reaction.body,false).length>0}
 function dragStart(e){if(e.button!==0&&e.pointerType!=='touch'||!hitBody(e.clientX,e.clientY))return;e.preventDefault();drag.active=true;drag.id=e.pointerId;drag.startX=e.clientX;drag.startY=e.clientY;drag.originX=interactionMode==='rotate'?viewYaw:drag.x;drag.originY=interactionMode==='rotate'?viewPitch:drag.y;drag.vx=drag.vy=0;drag.moved=false;drag.pushX=0;drag.pushY=1;renderer.domElement.setPointerCapture(e.pointerId);renderer.domElement.style.cursor='grabbing';container.dispatchEvent(new CustomEvent('avatar-drag',{detail:{phase:'start'}}));schedule()}
 function dragMove(e){if(!drag.active||e.pointerId!==drag.id)return;const r=renderer.domElement.getBoundingClientRect(),dx=e.clientX-drag.startX,dy=e.clientY-drag.startY;drag.moved||=Math.hypot(dx,dy)>5;if(interactionMode==='rotate'){viewYaw=drag.originX+dx*.012;viewPitch=drag.originY+dy*.012;viewQuaternion.setFromEuler(new THREE.Euler(viewPitch,viewYaw,0,'YXZ'));schedule();return}const length=Math.hypot(dx,dy);if(length>5){drag.pushX=dx/length;drag.pushY=-dy/length}const rawX=drag.originX+dx/r.width*(camera.right-camera.left),rawY=drag.originY-dy/r.height*(camera.top-camera.bottom),box=reaction.body.geometry.boundingBox,rx=Math.max(Math.abs(box.min.x),Math.abs(box.max.x)),ry=Math.max(Math.abs(box.min.y),Math.abs(box.max.y)),pad=reaction.fur?.userData.maskPad??0,limitX=Math.max(.1,camera.right-rx*1.12-pad-.06),limitY=Math.max(.1,camera.top-ry*1.12-pad-.06);if((Math.abs(rawX)>limitX||Math.abs(rawY)>limitY)&&performance.now()-impactAt>420){impactAt=performance.now();impactAxis=Math.abs(rawX)>limitX?'x':'y';impactSign=Math.sign(impactAxis==='x'?rawX:rawY);container.dispatchEvent(new CustomEvent('avatar-drag',{detail:{phase:'edge',axis:impactAxis,side:impactSign}}))}drag.x=Math.max(-limitX,Math.min(limitX,rawX));drag.y=Math.max(-limitY,Math.min(limitY,rawY));pointer={x:e.clientX,y:e.clientY};schedule()}
 function dragEnd(e){if(!drag.active||e.pointerId!==drag.id)return;drag.active=false;if(interactionMode==='play')releaseAt=performance.now();suppressClick=drag.moved;if(renderer.domElement.hasPointerCapture(e.pointerId))renderer.domElement.releasePointerCapture(e.pointerId);renderer.domElement.style.cursor='grab';container.dispatchEvent(new CustomEvent('avatar-drag',{detail:{phase:'end',moved:drag.moved}}));schedule()}
 const clickGuard=e=>{if(suppressClick){suppressClick=false;e.preventDefault();e.stopImmediatePropagation()}},touchGuard=e=>{const t=e.touches[0];if(t&&hitBody(t.clientX,t.clientY))e.preventDefault()};
 renderer.domElement.addEventListener('pointerdown',dragStart);renderer.domElement.addEventListener('pointermove',dragMove);renderer.domElement.addEventListener('pointerup',dragEnd);renderer.domElement.addEventListener('pointercancel',dragEnd);renderer.domElement.addEventListener('lostpointercapture',dragEnd);renderer.domElement.addEventListener('touchstart',touchGuard,{passive:false});container.addEventListener('click',clickGuard,true);
 container.addEventListener('pointerenter',enter);container.addEventListener('pointerleave',leave);window.addEventListener('pointermove',move,{passive:true});document.documentElement.addEventListener('pointerleave',windowLeave);still.addEventListener('change',mediaChange);fine.addEventListener('change',mediaChange);animate();
 return {
  update(resolved){
   if(disposed)return null;
   const g=resolveGeometry(resolved),next=new THREE.Group(),mat=bodyMaterial(resolved),bodyGeo=geometry(bodyMeshData(g)),body=new THREE.Mesh(bodyGeo,mat);bodyGeo.computeBoundingBox();next.add(body);
   const motionData=resolved.motion,baseLayout=motionData?.baseLayout??resolved.layout,baseMarks=motionData?.baseMarks??resolved.marks,eyeMarks=baseMarks.slice(-2),eyeMaterial=bodyMaterial({...resolved,marks:[{fill:resolved.marks.at(-1).fill}]}),eyeItems=[],browItems=[],furry=resolved.material?.preset==='fur';
   if(resolved.facePlate&&!furry){const points=pathPoints(resolved.facePlate.d),shape=new THREE.Shape(points.map(([x,y])=>new THREE.Vector2((x-g.cx)/32,(g.cy-y)/32))),flat=new THREE.ShapeGeometry(shape).toNonIndexed(),vertices=[];
    const triangle=(a,b,c,level)=>{if(level){const mid=(p,q)=>[(p[0]+q[0])/2,(p[1]+q[1])/2],ab=mid(a,b),bc=mid(b,c),ca=mid(c,a);triangle(a,ab,ca,level-1);triangle(ab,b,bc,level-1);triangle(ca,bc,c,level-1);triangle(ab,bc,ca,level-1)}else for(const p of [a,b,c])vertices.push(...p,surfaceDepth(...p,g)+.025)};
    const v=flat.attributes.position.array;for(let i=0;i<v.length;i+=9)triangle([v[i],v[i+1]],[v[i+3],v[i+4]],[v[i+6],v[i+7]],3);flat.dispose();const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));const normals=[];for(let i=0;i<vertices.length;i+=3){const x=vertices[i],y=vertices[i+1],h=.002,n=new THREE.Vector3(-(surfaceDepth(x+h,y,g)-surfaceDepth(x-h,y,g))/(2*h),-(surfaceDepth(x,y+h,g)-surfaceDepth(x,y-h,g))/(2*h),1).normalize();normals.push(n.x,n.y,n.z)}geo.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));next.add(new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:resolved.facePlate.fill,roughness:.65,side:THREE.DoubleSide})))}

   for(const eye of eyeMarks){
    if(furry){const item=createFurEye(furEyeDimensions(baseLayout).radius,mat.color,resolved.material.furLength);next.add(item.group);eyeItems.push({mesh:item.mesh,furry:item});continue}
    let eyeGeo;
    if(resolved.facePlate){const shape=new THREE.Shape(pathPoints(eye.d).map(([x,y])=>new THREE.Vector2((x-g.cx)/32,(g.cy-y)/32)));eyeGeo=new THREE.ExtrudeGeometry(shape,{depth:.012,bevelEnabled:false});{const p=eyeGeo.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,surfaceDepth(p.getX(i),p.getY(i),g)+.052+p.getZ(i))}}else eyeGeo=geometry(eyeMeshData(eye,g));
    const mesh=new THREE.Mesh(eyeGeo,eyeMaterial.clone());next.add(mesh);eyeItems.push({mesh,base:Float32Array.from(eyeGeo.attributes.position.array)});
   }
   for(const brow of furry?[]:resolved.brows??[]){let browGeo;if(resolved.facePlate){const shape=new THREE.Shape(pathPoints(brow.d).map(([x,y])=>new THREE.Vector2((x-g.cx)/32,(g.cy-y)/32)));browGeo=new THREE.ExtrudeGeometry(shape,{depth:.012,bevelEnabled:false});{const p=browGeo.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,surfaceDepth(p.getX(i),p.getY(i),g)+.052+p.getZ(i))}}else browGeo=geometry(eyeMeshData(brow,g));const mesh=new THREE.Mesh(browGeo,eyeMaterial.clone());mesh.userData.base=Float32Array.from(mesh.geometry.attributes.position.array);next.add(mesh);browItems.push(mesh)}eyeMaterial.dispose();
   let fur=null;if(resolved.material?.preset==='fur'){fur=makeFur(bodyGeo,g,resolved.marks.slice(-2),resolved.material,new THREE.Color(resolved.marks[0].fill).multiplyScalar(.9));next.add(fur)}
   for(const child of next.children){child.position.x+=(g.cx-50)/32;child.position.y+=(50-g.cy)/32}


   colorFrom=reaction?{head:reaction.body.material.color.clone(),eye:reaction.eyes[0].mesh.material.color.clone()}:null;
   fromPose=reaction?{...currentPose}:(motionData?.pose??IDENT);toPose=motionData?.pose??IDENT;currentPose=fromPose;morphTiming=resolved.config?.options?.expression&&resolved.config.options.expression!=='idle'?MORPH_IN:MORPH_OUT;morphStart=performance.now();
   reaction=motionData?{g,eyes:eyeItems,brows:browItems,baseLayout,seeds:motionData.seeds,reactionPoses:motionData.reactionPoses,body,fur,bodyColorTarget:mat.color.clone(),eyeColorTarget:eyeItems[0].mesh.material.color.clone(),expression:resolved.config?.options?.expression??'idle'}:null;
   scene.remove(avatar);disposeGroup(avatar);avatar=next;scene.add(avatar);if(raf){cancelAnimationFrame(raf);raf=0}animate();return {shape:resolved.shape,material:resolved.material?.preset??'resin'};
  },
  setEyesVisible(visible){if(reaction)for(const mesh of [...reaction.eyes.map(e=>e.furry?.group??e.mesh),...reaction.brows])mesh.visible=!!visible},
  capture({size,background}={}){if(disposed)return null;resize();freezeForCapture=true;if(raf){cancelAnimationFrame(raf);raf=0}morphStart=performance.now()-morphTiming.ms;animate();if(size){renderer.setPixelRatio(1);renderer.setSize(size,size,false);camera.left=-1.65;camera.right=1.65;camera.top=1.65;camera.bottom=-1.65;camera.updateProjectionMatrix()}if(background)renderer.setClearColor(background,1);renderer.render(scene,camera);const url=renderer.domElement.toDataURL('image/png');renderer.setClearColor(0x000000,0);renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));resize();freezeForCapture=false;return url},
  setTheme(value){if(disposed)return;theme=value;renderer.toneMappingExposure=theme==='dark'?1.15:1.08;renderer.render(scene,camera)},
  setMotion(value){motion=['none','hover','always'].includes(value)?value:'none';schedule()},
  setInteractionMode(value='rotate'){interactionMode=value==='play'?'play':'rotate';drag.active=false;drag.x=drag.y=drag.vx=drag.vy=0;impactAt=releaseAt=-1e9;gestureMix=0;if(interactionMode==='play'){viewYaw=viewPitch=0;viewQuaternion.identity();avatar.quaternion.identity()}schedule()},
  resetView(){viewYaw=viewPitch=0;viewQuaternion.identity();avatar.quaternion.identity();drag.x=drag.y=drag.vx=drag.vy=0;schedule()},
  setDraggable(value=true){drag.enabled=Boolean(value);renderer.domElement.style.cursor=drag.enabled?'grab':'default'},
  setGaze(value=true){gazeEnabled=Boolean(value);if(!gazeEnabled)pointer=null;schedule()},
  destroy(){if(disposed)return;clearTimeout(blinkTimer);document.removeEventListener('visibilitychange',visibilityChange);still.removeEventListener('change',visibilityChange);disposed=true;if(drag.id!==null&&renderer.domElement.hasPointerCapture(drag.id))renderer.domElement.releasePointerCapture(drag.id);drag.active=false;renderer.domElement.removeEventListener('pointerdown',dragStart);renderer.domElement.removeEventListener('pointermove',dragMove);renderer.domElement.removeEventListener('pointerup',dragEnd);renderer.domElement.removeEventListener('pointercancel',dragEnd);renderer.domElement.removeEventListener('lostpointercapture',dragEnd);renderer.domElement.removeEventListener('touchstart',touchGuard);container.removeEventListener('click',clickGuard,true);disposed=true;cancelAnimationFrame(raf);observer.disconnect();container.removeEventListener('pointerenter',enter);container.removeEventListener('pointerleave',leave);window.removeEventListener('pointermove',move);document.documentElement.removeEventListener('pointerleave',windowLeave);still.removeEventListener('change',mediaChange);fine.removeEventListener('change',mediaChange);disposeGroup(avatar);avatar.clear();reaction=null;scene.environment=null;scene.clear();env.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()}
 };
}


// Catalog thumbnails share one off-screen WebGL context. These are live-preview
// images; the configurator's final PNG export continues to use Blender.
export function createThumbnailRenderer(){
 const host=document.createElement('div');host.style.cssText='position:fixed;left:-10000px;top:0;width:112px;height:112px;pointer-events:none';document.body.append(host);const preview=createPreview(host);preview.setTheme('light');preview.setMotion('none');preview.setGaze(false);
 return {async render(resolved,{size=112,hideEyes=false}={}){host.style.width=host.style.height=Math.max(32,Math.min(512,size))+'px';preview.update(resolved);preview.setEyesVisible(!hideEyes);return preview.capture()},dispose(){preview.destroy();host.remove()}};
}
